package hdt9;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Sebastian Arriola 11463
 * @author Fernando Figueroa 14175
 * @author Jose Andres Areans 14470
 */
public class staInterfaz extends javax.swing.JFrame 
{
    
    SplayTreeMap<String, String> SteSplay;
    RBTreeMap<String, String> SteRBT;
    
    public staInterfaz()
    {
        initComponents();
        // por default se construye un arbol splay al iniciar
        construirSplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jBtn_EscogerArchivo = new javax.swing.JButton();
        jBtn_Traducir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtn_EscogerArbol = new javax.swing.JButton();
        jComboBox_Arboles = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hoja de Trabajo 9");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 350));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 230, 350));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 240, 350));

        jBtn_EscogerArchivo.setText("Escoger archivo para traducir");
        jBtn_EscogerArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_EscogerArchivoMouseClicked(evt);
            }
        });
        jPanel1.add(jBtn_EscogerArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, 30));

        jBtn_Traducir.setText("Traducir");
        jBtn_Traducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_TraducirMouseClicked(evt);
            }
        });
        jPanel1.add(jBtn_Traducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        jLabel1.setText("Diccionario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setText("Archivo a traducir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 20));

        jLabel3.setText("Traduccion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        jBtn_EscogerArbol.setText("Escoger");
        jBtn_EscogerArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EscogerArbolActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_EscogerArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        jComboBox_Arboles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Splay", "Red Black" }));
        jComboBox_Arboles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ArbolesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Arboles, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 130, -1));

        jLabel4.setText("Escoger arbol:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ArbolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ArbolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ArbolesActionPerformed

    private void jBtn_EscogerArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_EscogerArchivoMouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt", "text");
        fc.setFileFilter(filter);
        File file;
        int returnVal = fc.showOpenDialog(jPanel1);
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            file = fc.getSelectedFile();
            try {
                BufferedReader in = new BufferedReader(new FileReader(file));
                String line = in.readLine();
                while(line != null)
                {
                    jTextArea2.append(line + "\n");
                    line = in.readLine();
                }
                    
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(staInterfaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(staInterfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
    }//GEN-LAST:event_jBtn_EscogerArchivoMouseClicked

    private void jBtn_TraducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_TraducirMouseClicked
        String esp = null;
        String[] textotemp = jTextArea2.getText().split(" ");
        int i = 0;
        for(String temp1: textotemp)
        {
            temp1 = temp1.replace("\n", "");
            temp1 = temp1.replace(",", "");
            temp1 = temp1.replace(".", "");
            if(jComboBox_Arboles.getSelectedIndex() == 0) esp = SteSplay.get(temp1);
            else if(jComboBox_Arboles.getSelectedIndex() == 1) esp = SteRBT.get(temp1);
            if(esp == null)
            {
                jTextArea3.append("*" + temp1 + "*" + " ");
            }
            else
            {
                jTextArea3.append(esp + " ");
            }
            i++;
            if(i == 10)
            {
                i = 0;
                jTextArea3.append("\n");
            }
        }
    }//GEN-LAST:event_jBtn_TraducirMouseClicked

    private void jBtn_EscogerArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EscogerArbolActionPerformed

        if (jComboBox_Arboles.getSelectedIndex()==0) construirSplay();
        
        else if(jComboBox_Arboles.getSelectedIndex()==1) construirRBT();
        // limpiar jTxt_Area de parrafo traducido
        jTextArea3.setText("");
    }//GEN-LAST:event_jBtn_EscogerArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staInterfaz().setVisible(true);
            }
        });
    }
    
    protected void construirSplay()
    {
        SteSplay = new SplayTreeMap<>();
        Scanner s = null;
        try
        {
            s = new Scanner(new BufferedReader(new FileReader("src/engspa.dic")));
            while(s.hasNextLine())
            {
                String temp = s.nextLine();
                String[] Divisiones = temp.split("\t");
                String[] DivisionesSpa = Divisiones[1].split(";");
                jTextArea1.append(Divisiones[0] + " " + "=" + " " + DivisionesSpa[0] + "\n");
                if(SteSplay.contains(Divisiones[0]))
                {
                    continue;
                }
                else
                {
                    SteSplay.put(Divisiones[0], DivisionesSpa[0]);

                }
            }
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(staInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(s != null) s.close();
        }
    }
    
    protected void construirRBT()
    {
        SteRBT = new RBTreeMap<>();
        Scanner s = null;
        try
        {
            s = new Scanner(new BufferedReader(new FileReader("src/engspa.dic")));
            while(s.hasNextLine())
            {
                String temp = s.nextLine();
                String[] Divisiones = temp.split("\t");
                String[] DivisionesSpa = Divisiones[1].split(";");
                jTextArea1.append(Divisiones[0] + " " + "=" + " " + DivisionesSpa[0] + "\n");
                if(SteRBT.contains(Divisiones[0]))
                {
                    continue;
                }
                else
                {
                    SteRBT.put(Divisiones[0], DivisionesSpa[0]);

                }
            }
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(staInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(s != null) s.close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_EscogerArbol;
    private javax.swing.JButton jBtn_EscogerArchivo;
    private javax.swing.JButton jBtn_Traducir;
    private javax.swing.JComboBox<String> jComboBox_Arboles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
